// Inlines the ionicons SVGs we use into src/components/icons.generated.ts
import fs from 'node:fs';
const NAMES = `shield-checkmark shield-checkmark-outline lock-closed lock-open search-outline people-outline create-outline
checkmark-done checkmark arrow-back call-outline videocam-outline ellipsis-vertical add-circle-outline send mic-outline mic
videocam camera-reverse-outline volume-high call close qr-code key timer-outline image document-text camera people chatbubbles
chatbubbles-outline settings-outline play radio cloud-upload server phone-portrait finger-print eye-off checkmark-circle flash
sparkles mail-outline person-outline chatbubble-ellipses-outline cloud-done chevron-forward globe-outline skull flame
logo-apple logo-google-playstore download-outline`.split(/\s+/);
const out = {};
for (const n of NAMES) {
  const svg = fs.readFileSync(new URL(`../node_modules/ionicons/dist/svg/${n}.svg`, import.meta.url), 'utf8');
  out[n] = svg.replace(/<svg[^>]*>/, '').replace('</svg>', '');
}
fs.writeFileSync(
  new URL('../src/components/icons.generated.ts', import.meta.url),
  `// Generated by scripts/build-icons.mjs from the ionicons package\n// (the same icon set the app uses through @expo/vector-icons).\nexport const ICONS: Record<string, string> = ${JSON.stringify(out, null, 1)};\n`,
);
console.log(`${NAMES.length} icons`);
