/**
 * Bundled sticker packs. Images are original artwork generated by
 * scripts/generate-stickers.mjs and shipped inside the app, so a bundled
 * sticker is sent as a tiny {pack, id} reference inside the encrypted
 * payload - no upload, and the server learns nothing about which sticker.
 */

import type { StickerRef } from '../../shared/models/payloadExtensions';

export interface StickerDef extends StickerRef {
  emoji: string;
}

export interface StickerPack {
  id: string;
  title: string;
  stickers: StickerDef[];
}

const pack = (id: string, title: string, items: [string, string][]): StickerPack => ({
  id,
  title,
  stickers: items.map(([sid, emoji]) => ({ pack: id, id: sid, emoji })),
});

export const STICKER_PACKS: StickerPack[] = [
  pack('vero-faces', 'Vero Faces', [
    ['grin', '😀'],
    ['joy', '😂'],
    ['love', '😍'],
    ['wink', '😜'],
    ['cool', '😎'],
    ['wow', '😮'],
    ['sad', '😢'],
    ['cry', '😭'],
    ['angry', '😠'],
    ['think', '🤔'],
    ['sleepy', '😴'],
    ['party', '🥳'],
    ['blush', '😊'],
    ['kiss', '😘'],
    ['sweat', '😅'],
    ['starstruck', '🤩'],
  ]),
  pack('vero-things', 'Vero Things', [
    ['heart', '❤️'],
    ['broken-heart', '💔'],
    ['fire', '🔥'],
    ['star', '⭐'],
    ['rocket', '🚀'],
    ['coffee', '☕'],
    ['pizza', '🍕'],
    ['gift', '🎁'],
    ['cake', '🎂'],
    ['balloon', '🎈'],
    ['zap', '⚡'],
    ['check', '✅'],
    ['sun', '☀️'],
    ['moon', '🌙'],
    ['vero-shield', '🔒'],
    ['sparkles', '✨'],
  ]),
];

export const stickerKey = (ref: StickerRef) => `${ref.pack}/${ref.id}`;

export function findBundledSticker(ref: StickerRef): StickerDef | null {
  return STICKER_PACKS.find((p) => p.id === ref.pack)?.stickers.find((s) => s.id === ref.id) ?? null;
}
